# Generated by Django 5.2.7 on 2025-10-24 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0003_remove_pelicula_portada_pelicula_imagen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='es_estreno',
            field=models.BooleanField(default=False),
        ),
    ]
