# Generated by Django 5.2.7 on 2025-10-25 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0005_funcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='genero',
            field=models.CharField(choices=[('accion', 'Acción'), ('comedia', 'Comedia'), ('drama', 'Drama'), ('terror', 'Terror'), ('aventura', 'Aventura'), ('romance', 'Romance')], max_length=50),
        ),
    ]
