# Generated by Django 5.2.7 on 2025-10-26 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0007_puntuacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcion',
            name='capacidad',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
