# Generated by Django 5.2.7 on 2025-10-27 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0009_reserva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='genero',
            field=models.CharField(choices=[('accion', 'Acción'), ('comedia', 'Comedia'), ('drama', 'Drama'), ('terror', 'Terror'), ('aventura', 'Aventura'), ('romance', 'Romance'), ('ciencia_ficcion', 'Ciencia Ficción'), ('fantasia', 'Fantasía'), ('documental', 'Documental'), ('musical', 'Musical'), ('animacion', 'Animación'), ('suspenso', 'Suspenso'), ('historica', 'Histórica'), ('crimen', 'Crimen'), ('misterio', 'Misterio')], max_length=50),
        ),
        migrations.CreateModel(
            name='Asiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fila', models.CharField(max_length=1)),
                ('numero', models.IntegerField()),
                ('estado', models.CharField(choices=[('libre', 'Libre'), ('ocupado', 'Ocupado'), ('reservado', 'Reservado')], default='libre', max_length=10)),
                ('funcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asientos', to='peliculas.funcion')),
            ],
        ),
    ]
