# Generated by Django 5.2.7 on 2025-10-27 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0010_alter_pelicula_genero_asiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='asientos',
            field=models.ManyToManyField(blank=True, to='peliculas.asiento'),
        ),
    ]
