# Generated by Django 5.2.7 on 2025-10-29 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0011_reserva_asientos'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcion',
            name='formato',
            field=models.CharField(choices=[('2D', '2D'), ('3D', '3D'), ('IMAX', 'IMAX')], default='2D', max_length=10),
        ),
        migrations.AddField(
            model_name='funcion',
            name='idioma',
            field=models.CharField(choices=[('ES', 'Español'), ('SUB', 'Subtitulada')], default='ES', max_length=10),
        ),
        migrations.AddField(
            model_name='funcion',
            name='lleno',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='funcion',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
