# Generated by Django 5.2.7 on 2025-10-29 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0012_funcion_formato_funcion_idioma_funcion_lleno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcion',
            name='formato',
            field=models.CharField(choices=[('2D', '2D'), ('3D', '3D'), ('4D', '4D')], default='2D', max_length=10),
        ),
    ]
