# Generated by Django 5.2.7 on 2025-10-29 20:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0013_alter_funcion_formato'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pagada', 'Pagada'), ('cancelada', 'Cancelada'), ('validada', 'Validada')], default='pendiente', max_length=10),
        ),
        migrations.AddField(
            model_name='reserva',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 10, 29, 20, 3, 59, 780107, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr/'),
        ),
    ]
