# Generated by Django 5.2.7 on 2025-10-29 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0014_reserva_estado_reserva_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='mp_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='mp_preference_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
