# Generated by Django 5.2.7 on 2025-10-30 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0015_reserva_mp_payment_id_reserva_mp_preference_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='duracion',
            field=models.PositiveIntegerField(blank=True, help_text='Duración en minutos', null=True),
        ),
    ]
