# Generated by Django 5.2.7 on 2025-10-31 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0017_sala'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='activa',
            field=models.BooleanField(default=True),
        ),
    ]
