# Generated by Django 5.2.8 on 2025-12-12 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0018_sala_activa'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='card_brand',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='card_last4',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='installments',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='mp_status',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='mp_status_detail',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='payment_method',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='funcion',
            name='sala',
            field=models.CharField(choices=[('Sala 1', 'Sala 1'), ('Sala 2', 'Sala 2'), ('Sala 3', 'Sala 3'), ('Sala 4', 'Sala 4'), ('Sala 5', 'Sala 5'), ('Sala 6', 'Sala 6')], max_length=50),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='mp_payment_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='mp_preference_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
