# Generated by Django 5.2.8 on 2025-12-12 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0019_reserva_card_brand_reserva_card_last4_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=12, unique=True)),
                ('asiento', models.CharField(max_length=5)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entradas', to='peliculas.reserva')),
            ],
        ),
    ]
