# Generated by Django 5.2.8 on 2025-12-15 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0020_entrada'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='trailer_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
